// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: proto/news/news.proto

package news

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NewsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Id  string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_news_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_news_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_proto_news_news_proto_rawDescGZIP(), []int{0}
}

func (x *NewsItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NewsItem) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *NewsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNewsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys  []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Count uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetNewsReq) Reset() {
	*x = GetNewsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_news_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsReq) ProtoMessage() {}

func (x *GetNewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_news_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsReq.ProtoReflect.Descriptor instead.
func (*GetNewsReq) Descriptor() ([]byte, []int) {
	return file_proto_news_news_proto_rawDescGZIP(), []int{1}
}

func (x *GetNewsReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetNewsReq) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetNewsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*NewsItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetNewsRsp) Reset() {
	*x = GetNewsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_news_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsRsp) ProtoMessage() {}

func (x *GetNewsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_news_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsRsp.ProtoReflect.Descriptor instead.
func (*GetNewsRsp) Descriptor() ([]byte, []int) {
	return file_proto_news_news_proto_rawDescGZIP(), []int{2}
}

func (x *GetNewsRsp) GetItems() []*NewsItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetNewsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetNewsReq) Reset() {
	*x = SetNewsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_news_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNewsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNewsReq) ProtoMessage() {}

func (x *SetNewsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_news_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNewsReq.ProtoReflect.Descriptor instead.
func (*SetNewsReq) Descriptor() ([]byte, []int) {
	return file_proto_news_news_proto_rawDescGZIP(), []int{3}
}

func (x *SetNewsReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetNewsReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SetNewsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetNewsRsp) Reset() {
	*x = SetNewsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_news_news_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNewsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNewsRsp) ProtoMessage() {}

func (x *SetNewsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_news_news_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNewsRsp.ProtoReflect.Descriptor instead.
func (*SetNewsRsp) Descriptor() ([]byte, []int) {
	return file_proto_news_news_proto_rawDescGZIP(), []int{4}
}

var File_proto_news_news_proto protoreflect.FileDescriptor

var file_proto_news_news_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x6e, 0x65, 0x77,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e,
	0x65, 0x77, 0x73, 0x22, 0x3e, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x76, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x30, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x0c, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4e, 0x65,
	0x77, 0x73, 0x52, 0x73, 0x70, 0x32, 0x83, 0x01, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73,
	0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x73, 0x70,
	0x12, 0x39, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x77, 0x73,
	0x2e, 0x53, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x73, 0x70, 0x42, 0x14, 0x5a, 0x12, 0x69,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x3b, 0x6e, 0x65, 0x77,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_news_news_proto_rawDescOnce sync.Once
	file_proto_news_news_proto_rawDescData = file_proto_news_news_proto_rawDesc
)

func file_proto_news_news_proto_rawDescGZIP() []byte {
	file_proto_news_news_proto_rawDescOnce.Do(func() {
		file_proto_news_news_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_news_news_proto_rawDescData)
	})
	return file_proto_news_news_proto_rawDescData
}

var file_proto_news_news_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_news_news_proto_goTypes = []interface{}{
	(*NewsItem)(nil),   // 0: proto.news.NewsItem
	(*GetNewsReq)(nil), // 1: proto.news.GetNewsReq
	(*GetNewsRsp)(nil), // 2: proto.news.GetNewsRsp
	(*SetNewsReq)(nil), // 3: proto.news.SetNewsReq
	(*SetNewsRsp)(nil), // 4: proto.news.SetNewsRsp
}
var file_proto_news_news_proto_depIdxs = []int32{
	0, // 0: proto.news.GetNewsRsp.items:type_name -> proto.news.NewsItem
	1, // 1: proto.news.NewsService.GetNews:input_type -> proto.news.GetNewsReq
	3, // 2: proto.news.NewsService.SetNews:input_type -> proto.news.SetNewsReq
	2, // 3: proto.news.NewsService.GetNews:output_type -> proto.news.GetNewsRsp
	4, // 4: proto.news.NewsService.SetNews:output_type -> proto.news.SetNewsRsp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_news_news_proto_init() }
func file_proto_news_news_proto_init() {
	if File_proto_news_news_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_news_news_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_news_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_news_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_news_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNewsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_news_news_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNewsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_news_news_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_news_news_proto_goTypes,
		DependencyIndexes: file_proto_news_news_proto_depIdxs,
		MessageInfos:      file_proto_news_news_proto_msgTypes,
	}.Build()
	File_proto_news_news_proto = out.File
	file_proto_news_news_proto_rawDesc = nil
	file_proto_news_news_proto_goTypes = nil
	file_proto_news_news_proto_depIdxs = nil
}
