// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package news

import (
	"google.golang.org/protobuf/reflect/protoreflect"
	"im/proto/im"
)

// Injectors from wire.go:

func Request(message protoreflect.ProtoMessage) []byte {
	string2 := _wireStringValue
	imMessage := im.NewMessage(string2, message)
	v := im.Encode(imMessage)
	return v
}

var (
	_wireStringValue = "news"
)

func Response(message protoreflect.ProtoMessage) []byte {
	string2 := _wireStringValue2
	imMessage := im.NewMessage(string2, message)
	v := im.Encode(imMessage)
	return v
}

var (
	_wireStringValue2 = "news"
)
