// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: proto/room/room.proto

package room

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 通行证字段
type PassToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantCode string `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	RoomCode   string `protobuf:"bytes,2,opt,name=roomCode,proto3" json:"roomCode,omitempty"`
	UserType   string `protobuf:"bytes,3,opt,name=userType,proto3" json:"userType,omitempty"`
	UserId     uint64 `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName   string `protobuf:"bytes,5,opt,name=userName,proto3" json:"userName,omitempty"`
	UserThumb  string `protobuf:"bytes,6,opt,name=userThumb,proto3" json:"userThumb,omitempty"`
	UserTags   string `protobuf:"bytes,7,opt,name=userTags,proto3" json:"userTags,omitempty"`
}

func (x *PassToken) Reset() {
	*x = PassToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassToken) ProtoMessage() {}

func (x *PassToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassToken.ProtoReflect.Descriptor instead.
func (*PassToken) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *PassToken) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *PassToken) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *PassToken) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *PassToken) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PassToken) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PassToken) GetUserThumb() string {
	if x != nil {
		return x.UserThumb
	}
	return ""
}

func (x *PassToken) GetUserTags() string {
	if x != nil {
		return x.UserTags
	}
	return ""
}

// 消息格式-From
type From struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`           // 来源路径 $FrontierId.ConnId
	PassToken *PassToken `protobuf:"bytes,2,opt,name=passToken,proto3" json:"passToken,omitempty"` // 来源用户信息
}

func (x *From) Reset() {
	*x = From{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *From) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*From) ProtoMessage() {}

func (x *From) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use From.ProtoReflect.Descriptor instead.
func (*From) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *From) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *From) GetPassToken() *PassToken {
	if x != nil {
		return x.PassToken
	}
	return nil
}

// 消息格式-To
type To struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *To) Reset() {
	*x = To{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *To) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*To) ProtoMessage() {}

func (x *To) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use To.ProtoReflect.Descriptor instead.
func (*To) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{2}
}

func (x *To) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 消息格式
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type               string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                                  // 动作，空字符串，就是普通消息
	Content            string          `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                                                            // 内容
	ContentType        string          `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`                                                                                    // 内容类型
	ClientMsgId        uint64          `protobuf:"varint,4,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`                                                                                   // 客户端消息ID
	ServerMsgId        string          `protobuf:"bytes,5,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`                                                                                    // 服务端消息ID
	ServerMsgTimestamp uint64          `protobuf:"varint,6,opt,name=serverMsgTimestamp,proto3" json:"serverMsgTimestamp,omitempty"`                                                                     // 时间戳
	From               *From           `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`                                                                                                  // 源
	To                 *To             `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`                                                                                                      // 目标
	RuledOut           map[string]bool `protobuf:"bytes,9,rep,name=ruledOut,proto3" json:"ruledOut,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 排除需要推送的连接
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetClientMsgId() uint64 {
	if x != nil {
		return x.ClientMsgId
	}
	return 0
}

func (x *Message) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *Message) GetServerMsgTimestamp() uint64 {
	if x != nil {
		return x.ServerMsgTimestamp
	}
	return 0
}

func (x *Message) GetFrom() *From {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetTo() *To {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Message) GetRuledOut() map[string]bool {
	if x != nil {
		return x.RuledOut
	}
	return nil
}

// 消息记录的返回格式
type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type MakePassTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantCode string `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	TenantKey  string `protobuf:"bytes,2,opt,name=tenantKey,proto3" json:"tenantKey,omitempty"`
	RoomCode   string `protobuf:"bytes,3,opt,name=roomCode,proto3" json:"roomCode,omitempty"`
	UserType   string `protobuf:"bytes,4,opt,name=userType,proto3" json:"userType,omitempty"`
	UserId     uint64 `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName   string `protobuf:"bytes,6,opt,name=userName,proto3" json:"userName,omitempty"`
	UserThumb  string `protobuf:"bytes,7,opt,name=userThumb,proto3" json:"userThumb,omitempty"`
	UserTags   string `protobuf:"bytes,8,opt,name=userTags,proto3" json:"userTags,omitempty"`
}

func (x *MakePassTokenReq) Reset() {
	*x = MakePassTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakePassTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePassTokenReq) ProtoMessage() {}

func (x *MakePassTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePassTokenReq.ProtoReflect.Descriptor instead.
func (*MakePassTokenReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{5}
}

func (x *MakePassTokenReq) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *MakePassTokenReq) GetTenantKey() string {
	if x != nil {
		return x.TenantKey
	}
	return ""
}

func (x *MakePassTokenReq) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *MakePassTokenReq) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *MakePassTokenReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MakePassTokenReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MakePassTokenReq) GetUserThumb() string {
	if x != nil {
		return x.UserThumb
	}
	return ""
}

func (x *MakePassTokenReq) GetUserTags() string {
	if x != nil {
		return x.UserTags
	}
	return ""
}

type MakePassTokenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *MakePassTokenRsp) Reset() {
	*x = MakePassTokenRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakePassTokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePassTokenRsp) ProtoMessage() {}

func (x *MakePassTokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePassTokenRsp.ProtoReflect.Descriptor instead.
func (*MakePassTokenRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{6}
}

func (x *MakePassTokenRsp) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MakePassTokenRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MakePassTokenRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ViewPassTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ViewPassTokenReq) Reset() {
	*x = ViewPassTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewPassTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPassTokenReq) ProtoMessage() {}

func (x *ViewPassTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPassTokenReq.ProtoReflect.Descriptor instead.
func (*ViewPassTokenReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{7}
}

func (x *ViewPassTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ViewPassTokenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassToken *PassToken `protobuf:"bytes,1,opt,name=passToken,proto3" json:"passToken,omitempty"`
}

func (x *ViewPassTokenRsp) Reset() {
	*x = ViewPassTokenRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewPassTokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewPassTokenRsp) ProtoMessage() {}

func (x *ViewPassTokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewPassTokenRsp.ProtoReflect.Descriptor instead.
func (*ViewPassTokenRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{8}
}

func (x *ViewPassTokenRsp) GetPassToken() *PassToken {
	if x != nil {
		return x.PassToken
	}
	return nil
}

type JoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassToken  *PassToken `protobuf:"bytes,1,opt,name=passToken,proto3" json:"passToken,omitempty"`
	FrontierId uint64     `protobuf:"varint,2,opt,name=frontierId,proto3" json:"frontierId,omitempty"`
	ConnId     uint64     `protobuf:"varint,3,opt,name=connId,proto3" json:"connId,omitempty"`
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{9}
}

func (x *JoinReq) GetPassToken() *PassToken {
	if x != nil {
		return x.PassToken
	}
	return nil
}

func (x *JoinReq) GetFrontierId() uint64 {
	if x != nil {
		return x.FrontierId
	}
	return 0
}

func (x *JoinReq) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type JoinRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code          uint64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PassToken     *PassToken `protobuf:"bytes,3,opt,name=passToken,proto3" json:"passToken,omitempty"`
	LastMessageId string     `protobuf:"bytes,4,opt,name=lastMessageId,proto3" json:"lastMessageId,omitempty"`
}

func (x *JoinRsp) Reset() {
	*x = JoinRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRsp) ProtoMessage() {}

func (x *JoinRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRsp.ProtoReflect.Descriptor instead.
func (*JoinRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRsp) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinRsp) GetPassToken() *PassToken {
	if x != nil {
		return x.PassToken
	}
	return nil
}

func (x *JoinRsp) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

type LeaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassToken *PassToken `protobuf:"bytes,1,opt,name=passToken,proto3" json:"passToken,omitempty"`
}

func (x *LeaveReq) Reset() {
	*x = LeaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveReq) ProtoMessage() {}

func (x *LeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveReq.ProtoReflect.Descriptor instead.
func (*LeaveReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveReq) GetPassToken() *PassToken {
	if x != nil {
		return x.PassToken
	}
	return nil
}

type LeaveRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LeaveRsp) Reset() {
	*x = LeaveRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRsp) ProtoMessage() {}

func (x *LeaveRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRsp.ProtoReflect.Descriptor instead.
func (*LeaveRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveRsp) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUsersCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantCode string `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	RoomCode   string `protobuf:"bytes,2,opt,name=roomCode,proto3" json:"roomCode,omitempty"`
}

func (x *GetUsersCountReq) Reset() {
	*x = GetUsersCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersCountReq) ProtoMessage() {}

func (x *GetUsersCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersCountReq.ProtoReflect.Descriptor instead.
func (*GetUsersCountReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{13}
}

func (x *GetUsersCountReq) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetUsersCountReq) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

type GetUsersCountRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetUsersCountRsp) Reset() {
	*x = GetUsersCountRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersCountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersCountRsp) ProtoMessage() {}

func (x *GetUsersCountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersCountRsp.ProtoReflect.Descriptor instead.
func (*GetUsersCountRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{14}
}

func (x *GetUsersCountRsp) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetUsersCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrontierId uint64 `protobuf:"varint,1,opt,name=frontierId,proto3" json:"frontierId,omitempty"`
	TenantCode string `protobuf:"bytes,2,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	RoomCode   string `protobuf:"bytes,3,opt,name=roomCode,proto3" json:"roomCode,omitempty"`
	Count      uint64 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SetUsersCountReq) Reset() {
	*x = SetUsersCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUsersCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUsersCountReq) ProtoMessage() {}

func (x *SetUsersCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUsersCountReq.ProtoReflect.Descriptor instead.
func (*SetUsersCountReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{15}
}

func (x *SetUsersCountReq) GetFrontierId() uint64 {
	if x != nil {
		return x.FrontierId
	}
	return 0
}

func (x *SetUsersCountReq) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *SetUsersCountReq) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *SetUsersCountReq) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetUsersCountRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SetUsersCountRsp) Reset() {
	*x = SetUsersCountRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUsersCountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUsersCountRsp) ProtoMessage() {}

func (x *SetUsersCountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUsersCountRsp.ProtoReflect.Descriptor instead.
func (*SetUsersCountRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{16}
}

func (x *SetUsersCountRsp) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BroadcastReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BroadcastReq) Reset() {
	*x = BroadcastReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReq) ProtoMessage() {}

func (x *BroadcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReq.ProtoReflect.Descriptor instead.
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{17}
}

func (x *BroadcastReq) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type BroadcastRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BroadcastRsp) Reset() {
	*x = BroadcastRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRsp) ProtoMessage() {}

func (x *BroadcastRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRsp.ProtoReflect.Descriptor instead.
func (*BroadcastRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{18}
}

func (x *BroadcastRsp) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type RecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantCode    string `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	RoomCode      string `protobuf:"bytes,2,opt,name=roomCode,proto3" json:"roomCode,omitempty"`
	LastMessageId string `protobuf:"bytes,3,opt,name=lastMessageId,proto3" json:"lastMessageId,omitempty"`
	Count         uint64 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *RecordReq) Reset() {
	*x = RecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordReq) ProtoMessage() {}

func (x *RecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordReq.ProtoReflect.Descriptor instead.
func (*RecordReq) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{19}
}

func (x *RecordReq) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *RecordReq) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RecordReq) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *RecordReq) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecordRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record []*Message `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
}

func (x *RecordRsp) Reset() {
	*x = RecordRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_room_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRsp) ProtoMessage() {}

func (x *RecordRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_room_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRsp.ProtoReflect.Descriptor instead.
func (*RecordRsp) Descriptor() ([]byte, []int) {
	return file_proto_room_room_proto_rawDescGZIP(), []int{20}
}

func (x *RecordRsp) GetRecord() []*Message {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_proto_room_room_proto protoreflect.FileDescriptor

var file_proto_room_room_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x22, 0xd1, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x54, 0x61, 0x67, 0x73, 0x22, 0x4f, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x33, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x09, 0x70,
	0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x18, 0x0a, 0x02, 0x54, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x8f, 0x03, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x46, 0x72,
	0x6f, 0x6d, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x54, 0x6f, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x3d, 0x0a, 0x08, 0x72, 0x75, 0x6c, 0x65,
	0x64, 0x4f, 0x75, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x72,
	0x75, 0x6c, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x1a, 0x3b, 0x0a, 0x0d, 0x52, 0x75, 0x6c, 0x65, 0x64,
	0x4f, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xf6, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x6b,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x54,
	0x68, 0x75, 0x6d, 0x62, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x61, 0x67,
	0x73, 0x22, 0x56, 0x0a, 0x10, 0x4d, 0x61, 0x6b, 0x65, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28, 0x0a, 0x10, 0x56, 0x69, 0x65,
	0x77, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x10, 0x56, 0x69, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x76, 0x0a, 0x07,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x6e, 0x49, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33,
	0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50,
	0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x08, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x09, 0x70, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x38, 0x0a, 0x08, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x4e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x84,
	0x01, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x3d, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3d,
	0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2d,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x83, 0x01,
	0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x73, 0x70,
	0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x32, 0xa1, 0x04,
	0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a,
	0x0d, 0x4d, 0x61, 0x6b, 0x65, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x61, 0x6b, 0x65,
	0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x0d, 0x56, 0x69,
	0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x61, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x05, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x73, 0x70, 0x12, 0x4b,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x0d, 0x53,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x73,
	0x70, 0x42, 0x1a, 0x5a, 0x18, 0x77, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x69, 0x6d, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x3b, 0x72, 0x6f, 0x6f, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_room_room_proto_rawDescOnce sync.Once
	file_proto_room_room_proto_rawDescData = file_proto_room_room_proto_rawDesc
)

func file_proto_room_room_proto_rawDescGZIP() []byte {
	file_proto_room_room_proto_rawDescOnce.Do(func() {
		file_proto_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_room_room_proto_rawDescData)
	})
	return file_proto_room_room_proto_rawDescData
}

var file_proto_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_room_room_proto_goTypes = []interface{}{
	(*PassToken)(nil),        // 0: proto.room.PassToken
	(*From)(nil),             // 1: proto.room.From
	(*To)(nil),               // 2: proto.room.To
	(*Message)(nil),          // 3: proto.room.Message
	(*Record)(nil),           // 4: proto.room.Record
	(*MakePassTokenReq)(nil), // 5: proto.room.MakePassTokenReq
	(*MakePassTokenRsp)(nil), // 6: proto.room.MakePassTokenRsp
	(*ViewPassTokenReq)(nil), // 7: proto.room.ViewPassTokenReq
	(*ViewPassTokenRsp)(nil), // 8: proto.room.ViewPassTokenRsp
	(*JoinReq)(nil),          // 9: proto.room.JoinReq
	(*JoinRsp)(nil),          // 10: proto.room.JoinRsp
	(*LeaveReq)(nil),         // 11: proto.room.LeaveReq
	(*LeaveRsp)(nil),         // 12: proto.room.LeaveRsp
	(*GetUsersCountReq)(nil), // 13: proto.room.GetUsersCountReq
	(*GetUsersCountRsp)(nil), // 14: proto.room.GetUsersCountRsp
	(*SetUsersCountReq)(nil), // 15: proto.room.SetUsersCountReq
	(*SetUsersCountRsp)(nil), // 16: proto.room.SetUsersCountRsp
	(*BroadcastReq)(nil),     // 17: proto.room.BroadcastReq
	(*BroadcastRsp)(nil),     // 18: proto.room.BroadcastRsp
	(*RecordReq)(nil),        // 19: proto.room.RecordReq
	(*RecordRsp)(nil),        // 20: proto.room.RecordRsp
	nil,                      // 21: proto.room.Message.RuledOutEntry
}
var file_proto_room_room_proto_depIdxs = []int32{
	0,  // 0: proto.room.From.passToken:type_name -> proto.room.PassToken
	1,  // 1: proto.room.Message.from:type_name -> proto.room.From
	2,  // 2: proto.room.Message.to:type_name -> proto.room.To
	21, // 3: proto.room.Message.ruledOut:type_name -> proto.room.Message.RuledOutEntry
	0,  // 4: proto.room.ViewPassTokenRsp.passToken:type_name -> proto.room.PassToken
	0,  // 5: proto.room.JoinReq.passToken:type_name -> proto.room.PassToken
	0,  // 6: proto.room.JoinRsp.passToken:type_name -> proto.room.PassToken
	0,  // 7: proto.room.LeaveReq.passToken:type_name -> proto.room.PassToken
	3,  // 8: proto.room.BroadcastReq.message:type_name -> proto.room.Message
	3,  // 9: proto.room.BroadcastRsp.message:type_name -> proto.room.Message
	3,  // 10: proto.room.RecordRsp.record:type_name -> proto.room.Message
	5,  // 11: proto.room.RoomService.MakePassToken:input_type -> proto.room.MakePassTokenReq
	7,  // 12: proto.room.RoomService.ViewPassToken:input_type -> proto.room.ViewPassTokenReq
	9,  // 13: proto.room.RoomService.Join:input_type -> proto.room.JoinReq
	11, // 14: proto.room.RoomService.Leave:input_type -> proto.room.LeaveReq
	13, // 15: proto.room.RoomService.GetUsersCount:input_type -> proto.room.GetUsersCountReq
	15, // 16: proto.room.RoomService.SetUsersCount:input_type -> proto.room.SetUsersCountReq
	17, // 17: proto.room.RoomService.Broadcast:input_type -> proto.room.BroadcastReq
	19, // 18: proto.room.RoomService.Record:input_type -> proto.room.RecordReq
	6,  // 19: proto.room.RoomService.MakePassToken:output_type -> proto.room.MakePassTokenRsp
	8,  // 20: proto.room.RoomService.ViewPassToken:output_type -> proto.room.ViewPassTokenRsp
	10, // 21: proto.room.RoomService.Join:output_type -> proto.room.JoinRsp
	12, // 22: proto.room.RoomService.Leave:output_type -> proto.room.LeaveRsp
	14, // 23: proto.room.RoomService.GetUsersCount:output_type -> proto.room.GetUsersCountRsp
	16, // 24: proto.room.RoomService.SetUsersCount:output_type -> proto.room.SetUsersCountRsp
	18, // 25: proto.room.RoomService.Broadcast:output_type -> proto.room.BroadcastRsp
	20, // 26: proto.room.RoomService.Record:output_type -> proto.room.RecordRsp
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_room_room_proto_init() }
func file_proto_room_room_proto_init() {
	if File_proto_room_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_room_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*From); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*To); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakePassTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakePassTokenRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewPassTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewPassTokenRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersCountRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUsersCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUsersCountRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_room_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_room_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_room_proto_goTypes,
		DependencyIndexes: file_proto_room_room_proto_depIdxs,
		MessageInfos:      file_proto_room_room_proto_msgTypes,
	}.Build()
	File_proto_room_room_proto = out.File
	file_proto_room_room_proto_rawDesc = nil
	file_proto_room_room_proto_goTypes = nil
	file_proto_room_room_proto_depIdxs = nil
}
